"""add normalized output column to agents runs table

Revision ID: 2615c4ae2283
Revises: 3fa528cf3632
Create Date: 2026-03-14 02:04:35.488710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2615c4ae2283'
down_revision: Union[str, Sequence[str], None] = '3fa528cf3632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('normalized_payload', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('schema_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'schema_name')
    op.drop_column('agent_runs', 'normalized_payload')
    # ### end Alembic commands ###
