"""add scrape tables

Revision ID: 342907a9ebc9
Revises: 2615c4ae2283
Create Date: 2026-03-15 01:09:15.515659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342907a9ebc9'
down_revision: Union[str, Sequence[str], None] = '2615c4ae2283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_source_id'), 'scrape_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('scraped_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_run_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_documents_checksum'), 'scraped_documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_scraped_documents_scrape_run_id'), 'scraped_documents', ['scrape_run_id'], unique=False)
    op.create_table('extracted_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['scraped_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_entities_document_id'), 'extracted_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_entities_entity_type'), 'extracted_entities', ['entity_type'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['scraped_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_tasks_agent_type'), 'processing_tasks', ['agent_type'], unique=False)
    op.create_index(op.f('ix_processing_tasks_document_id'), 'processing_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_status'), 'processing_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_tasks_status'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_document_id'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_agent_type'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index(op.f('ix_extracted_entities_entity_type'), table_name='extracted_entities')
    op.drop_index(op.f('ix_extracted_entities_document_id'), table_name='extracted_entities')
    op.drop_table('extracted_entities')
    op.drop_index(op.f('ix_scraped_documents_scrape_run_id'), table_name='scraped_documents')
    op.drop_index(op.f('ix_scraped_documents_checksum'), table_name='scraped_documents')
    op.drop_table('scraped_documents')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_source_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
