"""add agent runs tools used

Revision ID: 3fa528cf3632
Revises: ea8d16081701
Create Date: 2026-03-13 22:51:27.900795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa528cf3632'
down_revision: Union[str, Sequence[str], None] = 'ea8d16081701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('call_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('started', 'success', 'failed', name='agent_run_tool_status'), server_default='started', nullable=False),
    sa.Column('tool_input', sa.Text(), nullable=True),
    sa.Column('tool_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_tools_run_id'), 'agent_run_tools', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_run_tools_tool_name'), 'agent_run_tools', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_run_tools_tool_name'), table_name='agent_run_tools')
    op.drop_index(op.f('ix_agent_run_tools_run_id'), table_name='agent_run_tools')
    op.drop_table('agent_run_tools')
    # ### end Alembic commands ###
